### PR TITLE
Mansions seed filter

### PR DESCRIPTION
**Pull request by Treer**
Moulins fork of amidst seems to be the furthest ahead of the main project at the moment, so I will see if I can use it instead - it has a refactoring that might be useful for what I'm doing.

If you see this Moulins, I'm not sure of the purpose of your fork (are you just keeping a more up-to-date version of Amidst going?) and I couldn't find an email address.

### CODE REVIEW

**Comment by moulins** [comment]
@Treer: My fork is mainly to host my seed filter implementation, and most of the refactorings are there to support it. I have tried to keep the fork compatible with the last Minecraft versions, but this is not its main goal.

Unless you want to use the seed search feature (which is still incomplete), I would recommend instead that you cherry-pick the refactorings that you need.

If you need to discuss more, we can either do it here, or I can send you an email through the address mentioned on your profile.

--------

P.S.: I don't know how you did it, but you managed to merge back your changes into my [woodland-mansions](https://github.com/moulins/amidst/commits/woodland-mansions) branch (it's actually how I found out about this :stuck_out_tongue:). I don't think I have given any rights to anybody on my fork, so do you know what happened? (maybe a github bug?)

**Comment by Treer** [comment]
Wow. That is interesting.

I created a pull request to my fork, which needed conflicts resolved because I've changed a lot, so I resolved them using Github's web editor (as the pull request hasn't changed my fork at this point, it still only existed in github), I assume using their editor is why the change has "verified" next to it.

If you haven't given rights to eveyone then this smells like a Github bug, however I'm not the most experienced person with github, and I believe I have the ability to merge pull requests in the upstream toolbox4minecraft/amidst repo, that might have leaked somehow.

**Comment by moulins** [comment]
> I created a pull request to my fork, which needed conflicts resolved because I've changed a lot, so I resolved them using Github's web editor (as the pull request hasn't changed my fork at this point, it still only existed in github), I assume using their editor is why the change has "verified" next to it.

In fact, I received the notification today at 13h54 UTC, which seems to correlate with your PR #4 (and this PR is actually merging the branch which got corrupted on my side). Did you follow the same steps for #4 as you did here?

**Comment by Treer** [comment]
No, the PR here was to a branch I created that had no changes, so the PR didn't need any conflicts resolved before merging.

**Pull request merged**
